title: David DukiÄ‡
description: Postdoctoral NLP researcher at TakeLab, University of Zagreb, Croatia
logo: /assets/img/logo.jpg
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Social media links - will appear under your description
social:
  - name: LinkedIn
    url: https://www.linkedin.com/in/david-duki%C4%87-7a86391a3/
    icon: linkedin
  - name: Google Scholar
    url: https://scholar.google.com/citations?user=pHg6PjQAAAAJ&hl=en
    icon: google-scholar
  - name: X
    url: https://x.com/ddaviddukic
    icon: x-twitter
  - name: Bluesky
    url: https://bsky.app/profile/ddaviddukic.bsky.social
    icon: bluesky
  - name: Mail
    url: mailto:david.dukic@fer.hr
    icon: envelope